name = "gotoolkit"
main = "index.js"
compatibility_date = "2024-12-01"
workers_dev = true
# Add your Cloudflare account information before deploying (account_id, zone_id, routes)
# account_id = "bdcd0c3bac2cc9b0280d71a911b2b74f"
# route = "https://gotoolkit.web.app/*"
