name = "gotoolkit-openai-proxy"
main = "index.js"
compatibility_date = "2024-12-01"
workers_dev = true

# Configure account_id, zone_id, and routes before deploying.
# account_id = "bdcd0c3bac2cc9b0280d71a911b2b74f"
# route = "https://gotoolkit.web.app/*"
